# SPDX-License-Identifier: ISC
# SPDX-FileCopyrightText: (c) 2019 Anil Madhavapeddy <anil@recoil.org>
name: Builds, tests & co

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'pull_request' || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    permissions:
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
        ocaml-compiler:
          - 5
          - ocaml-variants.5.3.0+options,ocaml-option-flambda

    runs-on: ${{ matrix.os }}

    steps:
      - name: Switch to GCC 14
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Initialize git submodules
        run: git submodule update --init --recursive

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Initialize git submodules
        run: git submodule update --init --recursive
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-opam@v3
